version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: makenson
      MYSQL_DATABASE: stori_db
      MYSQL_USER: makenson
      MYSQL_PASSWORD: makenson
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    command: /wait-for-it.sh db:33060 -- python /app/src/main.py
    environment:
      - DATABASE_URL=mysql+pymysql://makenson:makenson@db:3306/stori_db
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/app

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
